### ISSUE TITLE
Document what deserializers are

### ISSUE THREAD

**Issue by derneuere** [kaedroho/django-render#19]
In the example project "deserializers" are [referenced](https://github.com/kaedroho/djangopress/tree/main/client/src/deserializers) and used, but they are not explained in the documentation. 

When do I have to use them? Are they optional? What problem do they solve?

**Comment by kaedroho** [comment]
Thanks for raising!

**Comment by kaedroho** [comment]
I've renamed these to "adapters" to match their name in Python. Documentation added here: https://django-render.org/docs/python2react/
